# Generated by Django 4.0.1 on 2022-06-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('school_address', models.CharField(max_length=200)),
                ('academic_level', models.CharField(max_length=100)),
                ('year_of_completion', models.DateField(null=True)),
                ('reason_for_application', models.TextField()),
                ('recomendation', models.FileField(upload_to='recomendation')),
                ('birth_certificate', models.FileField(upload_to='files')),
                ('national_id', models.FileField(upload_to='files')),
                ('sponsor', models.TextField(max_length=200, null=True)),
                ('applicationDate', models.DateField(auto_now_add=True)),
                ('staffapproval', models.BooleanField(default=False)),
                ('sponsorshipStatus', models.BooleanField(default=False)),
            ],
        ),
    ]
