# Generated by Django 4.0.1 on 2022-06-24 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applications',
            old_name='sponsorshipStatus',
            new_name='sponsorshipApproval',
        ),
        migrations.RenameField(
            model_name='applications',
            old_name='idno',
            new_name='user',
        ),
    ]
