# Generated by Django 4.0.1 on 2022-06-24 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_rename_user_applications_idno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applications',
            old_name='idno',
            new_name='user',
        ),
    ]
